spring:
  application:
    name: springms-sidecar
server:
  port: 8210
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
sidecar:
  port: 1337
  health-uri: http://localhost:1337/api/health
